### ISSUE TITLE
读后感-《人人都是产品经理》

### ISSUE THREAD

**Issue by Kingfish404** [Kingfish404/kingfish404.github.io#12]
https://blog.achacker.com/PM01/#top 

 软件需求分析课程的作业，要求阅读苏杰的《人人都是产品经理》，由于发现最近已经出了2.0，本着用新不用旧的原则，我选择了2.0作为我的阅读书籍，并以阅读为基础，写了这片读后感。

**Comment by october-rain** [comment]
996
