### ISSUE TITLE
智能算法-模拟退火-粒子群-鱼群算法

### ISSUE THREAD

**Issue by Kingfish404** [Kingfish404/kingfish404.github.io#9]
https://blog.achacker.com/IntelligentAlgorithm/#top 

 这几天看了几个智能算法,并且试着自己写了下,个人感觉这几个算法有许多的相似之处,那就是都是通过某种随机函数来对已有结果进行改变,建立某种评估函数(如适应度函数),然后再通过某种函数对其进行筛选,并将前两者循环多次,即可得到优化后的值。

智能算法在大多数的情况下都只能得到最优解的近似值,并且可能会陷入到局部最优解当中。

**Comment by LKJ-hbut** [comment]
Great!
